name: Tests and Deployment

on:
    push:
        branches:
            - master

jobs:
    publish-npm:
        needs: test-and-coverage
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2.1.5
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npm run build
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}